---
attributes: ~
driver:
  associate_public_ip: true
  instance_type: t2.micro
  name: ec2
  region: eu-west-2
  require_chef_omnibus: true
platforms:
  -
    driver:
      box: ubuntu/xenial64
    name: ubuntu-18.04
suites:
  -
    name: default
    run_list:
      - "recipe[uber-app::default]"
    verifier:
      inspec_tests:
        - test/integration/default
verifier:
  name: inspec
