---
driver:
  associate_public_ip: true
  instance_type: t2.micro
  name: ec2
  region: eu-west-2
  require_chef_omnibus: true
  subnet_id: subnet-3fd92344
platforms:
  -
    name: ubuntu-16.04
provisioner:
  always_update_cookbooks: true
  chef_license: accept-no-persist
  log_level: info
  name: chef_zero
  product_name: chef
  product_version: "14.10.9"
suites:
  -
    attributes: ~
    name: default
    run_list:
      - "recipe[uber-app::default]"
    verifier:
      chef_license: accept-no-persist
      inspec_tests:
        - test/integration/default
verifier:
  chef_license: accept-no-persist
  name: inspec
