---
driver:
  name: vagrant
platforms:
  -
    name: ubuntu-18.04
provisioner:
  always_update_cookbooks: true
  chef_license: accept-no-persist
  log_level: info
  name: chef_zero
  product_name: chef
  product_version: 14.10.9
suites:
  -
    attributes: ~
    name: default
    run_list:
      - "recipe[uber-app::default]"
    verifier:
      chef_license: accept-no-persist
      inspec_tests:
        - test/integration/default
verifier:
  chef_license: accept-no-persist
  name: inspec
