---
  driver:
    name: ec2
    region: eu-west-2
    require_chef_omnibus: true
    instance_type: t2.micro
    subnet_id: subnet-0e9b6138ff1ce18f2
    associate_public_ip: true


  verifier:
    name: inspec

  platforms:
<<<<<<< HEAD
    name: [ubuntu-16.04]
    driver:
      box: ubuntu/xenial64
=======
    name: ubuntu/xenial64
>>>>>>> ef9f708aad062265d3a708bd0b76270bf3bf1331

  suites:
    name: default
    run_list:
      - recipe[uber-app::default]
    verifier:
      inspec_tests:
        - test/integration/default
  attributes:
